"""empty message

Revision ID: cc193dff07f7
Revises: 77446136d012
Create Date: 2022-08-18 10:15:17.574801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc193dff07f7'
down_revision = '77446136d012'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
#     op.drop_column('artist', 'seeking_venue')
#     op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
#     op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_venue')
    op.add_column('artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###
